/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "iuxufaqtdhshdpxayhjn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1eHVmYXF0ZGhzaGRweGF5aGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY5MTc1OTUsImV4cCI6MjA4MjQ5MzU5NX0.NIhd-FKA6-Gp_rXwRfET0A9AiBnVwo4LD8R3qbIlgWA"